source/accounts/urls.py
from django.urls import path
from accounts.views import login_view, logout_view, register_view, UserDetailView, UserChangeView, UserChangePasswordView, AllUsers


urlpatterns = [
    path('login/', login_view, name='login'),
    path('logout/', logout_view, name='logout'),
    path('register/', register_view, name='register'),
    path('profile/<int:pk>/', UserDetailView.as_view(), name='detail'),
    path('profile/<int:pk>/edit/', UserChangeView.as_view(), name='user_update'),
    path('profile/<int:pk>/change-password/', UserChangePasswordView.as_view(), name='user_change_password'),
    path('progile/all/', AllUsers.as_view(), name='all_users')
]


app_name = 'accounts'

source/main/urls.py
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include
from django.conf import settings

urlpatterns = [

                  path('admin/', admin.site.urls),

                  path('accounts/', include('accounts.urls')),

                  path('', include('webapp.urls')),

                  path('api/v2/', include('api_v2.urls'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.contrib import admin
from django.urls import path
from webapp.views import *

app_name = 'webapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPage.as_view(), name='main_url'),
    path('task/<int:pk>/', TaskDetails.as_view(), name='task_details_url'),
    path('task/create/', TaskCreate.as_view(), name='task_create_url'),
    path('task/edit/<int:pk>/', TaskEdit.as_view(), name='task_edit_url'),
    path('task/delete/<int:pk>/', TaskDelete.as_view(), name='task_delete_url'),
    path('status/', StatusView.as_view(), name='status_url'),
    path('type/', TypeView.as_view(), name='type_url'),
    path('type/create/', TypeCreate.as_view(), name='type_create_url'),
    path('status/create/', StatusCreate.as_view(), name='status_create_url'),
    path('status/edit/<int:pk>/', StatusEdit.as_view(), name='status_edit_url'),
    path('status/delete/<int:pk>/', StatusDelete.as_view(), name='status_delete_url'),
    path('type/edit/<int:pk>', TypeEdit.as_view(), name='type_edit_url'),
    path('type/delete/<int:pk>/', TypeDelete.as_view(), name='type_delete_url'),
    path('project/', ProjectView.as_view(), name='project_url'),
    path('project/<int:pk>/', ProjectDetails.as_view(), name='project_details_url'),
    path('project/edit/<int:pk>/', ProjectEdit.as_view(), name='project_edit_url'),
    path('project/delete/<int:pk>/', ProjectDelete.as_view(), name='project_delete_url'),
    path('project/create/', ProjectCreate.as_view(), name='project_create_url'),
    path('project/user/delete/<str:user_1>/<int:id>/', TeamUserDel.as_view(), name='team_user_del_url')
]

source/accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# class Token(models.Model):
#     token = models.UUIDField(verbose_name='Token', default=uuid4)
#     user = models.ForeignKey('auth.User', related_name='registration_tokens',
#                              verbose_name='User', on_delete=models.CASCADE)
#
#     def __str__(self):
#         return str(self.token)


class Profile(models.Model):
    user = models.OneToOneField(User, related_name='profile', on_delete=models.CASCADE, verbose_name='Пользователь')
    birth_date = models.DateField(null=True, blank=True, verbose_name='Дата рождения')
    avatar = models.ImageField(null=True, blank=True, upload_to='user_pics', verbose_name='Аватар')
    about = models.TextField(max_length=500, blank=True, null=True, verbose_name='О себе')
    git_hub = models.URLField(null=True, blank=True, verbose_name='Github')

    def __str__(self):
        return self.user.get_full_name() + "'s Profile"

    class Meta:
        verbose_name = 'Профиль'
        verbose_name_plural = 'Профили'

source/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class SignUpForm(forms.Form):
    username = forms.CharField(max_length=100, required=True, label='Username')
    password = forms.CharField(max_length=100, required=True, label='Password',
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, required=True, label='Password confirm',
                                       widget=forms.PasswordInput)
    email = forms.EmailField(required=True, label='Email' )
    first_name = forms.CharField(max_length=100, label='First name', required=False)
    second_name = forms.CharField(max_length=100, label='Second Name', required=False)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        try:
            User.objects.get(username=username)
            raise ValidationError('Username already taken.', code='username_taken')
        except User.DoesNotExist:
            return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        try:
            User.objects.get(email=email)
            raise ValidationError('Email already registered.', code='email_registered')
        except User.DoesNotExist:
            return email

    def clean_second_name(self):
        f_name = self.cleaned_data.get('first_name')
        s_name = self.cleaned_data.get('second_name')
        print(f_name, s_name)
        if not (f_name or s_name):
            raise ValidationError('Enter First or Second name')

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data.get('password')
        password_2 = self.cleaned_data.get('password_confirm')
        if password_1 != password_2:
            raise ValidationError('Passwords do not match.', code='passwords_do_not_match')
        return self.cleaned_data



class UserChangeForm(forms.ModelForm):
    avatar = forms.ImageField(label='Аватар', required=False)
    birth_date = forms.DateField(label='День рождения', input_formats=['%Y-%m-%d', '%d.%m.%Y'], required=False)
    about = forms.CharField(label='О себе', required=False)
    git_hub = forms.URLField(required=False, widget=forms.TextInput(attrs={'placeholder': 'http://github.com/<username>/'}))

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'avatar', 'birth_date', 'about', 'git_hub']
        profile_fields = ['avatar', 'birth_date', 'about', 'git_hub']

        labels = {'first_name': 'Имя', 'last_name': 'Фамилия', 'email': 'Email'}

    def clean_git_hub(self):
        git_hub = self.cleaned_data.get('git_hub')
        print(git_hub)
        if git_hub[:17]!='http://github.com' and git_hub[:18]!='https://github.com':
            raise ValidationError('Please enter: http://github.com/<username>')
        else:
            return git_hub

    def save(self, commit=True):

        user = super().save(commit)

        self.save_profile(commit)

        return user

    def save_profile(self, commit=True):

        profile = self.instance.profile

        for field in self.Meta.profile_fields:
            setattr(profile, field, self.cleaned_data[field])

        if not profile.avatar:
            profile.avatar = None

        if commit:
            profile.save()

    def get_initial_for_field(self, field, field_name):

        if field_name in self.Meta.profile_fields:
            return getattr(self.instance.profile, field_name)

        return super().get_initial_for_field(field, field_name)


class UserChangePasswordForm(forms.ModelForm):
    password = forms.CharField(max_length=100, required=True, label='New Password',
                               widget=forms.PasswordInput)
    password_confirm = forms.CharField(max_length=100, required=True, label='New Password confirm',
                                       widget=forms.PasswordInput)
    old_password = forms.CharField(max_length=100, required=True, label='Old Password',
                                   widget=forms.PasswordInput)

    def clean_old_password(self):
        old_password = self.cleaned_data.get('old_password')
        user = self.instance
        if not user.check_password(old_password):
            raise ValidationError('Invalid password.', code='invalid_password')
        return old_password

    def clean(self):
        super().clean()
        password_1 = self.cleaned_data.get('password')
        password_2 = self.cleaned_data.get('password_confirm')
        if password_1 != password_2:
            raise ValidationError('Passwords do not match.', code='passwords_do_not_match')
        return self.cleaned_data

    def save(self, commit=True):
        user = self.instance
        user.set_password(self.cleaned_data.get('password'))
        if commit:
            user.save()
        return user

    class Meta:
        model = User
        fields = ['password', 'password_confirm', 'old_password']

source/accounts/views.py
from django.contrib.auth.mixins import UserPassesTestMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.urls import reverse
from django.views.generic import DetailView, UpdateView, ListView
from .models import Profile
from accounts.forms import SignUpForm, UserChangePasswordForm, UserChangeForm


def login_view(request):
    context = {}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            next_url = request.GET.get('next', '')
            if next_url:
                return redirect(next_url)
            return redirect('webapp:main_url')
        else:
            context['has_error'] = True
    return render(request, 'login.html', context=context)


def logout_view(request):
    logout(request)
    return redirect('webapp:main_url')


def register_view(request):
    if request.method == 'GET':
        form = SignUpForm()
        return render(request, 'register.html', context={'form': form})
    elif request.method == 'POST':
        form = SignUpForm(data=request.POST)
        if form.is_valid():
            user = User(
                username=form.cleaned_data.get('username'),
                email=form.cleaned_data.get('email'),
                is_active=True
            )
            user.set_password(form.cleaned_data.get('password'))
            user.save()
            Profile.objects.create(user=user)

            return redirect('webapp:main_url')
        else:
            return render(request, 'register.html', context={'form': form})


class UserDetailView(DetailView):
    model = User
    template_name = 'user_detail.html'
    context_object_name = 'user_obj'


class UserChangeView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_update.html'
    context_object_name = 'user_obj'
    form_class = UserChangeForm

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:detail', kwargs={'pk': self.object.pk})


class UserChangePasswordView(UserPassesTestMixin, UpdateView):
    model = User
    template_name = 'user_change_password.html'
    form_class = UserChangePasswordForm
    context_object_name = 'user_obj'

    def test_func(self):
        return self.get_object() == self.request.user

    def get_success_url(self):
        return reverse('accounts:login')


class AllUsers(ListView):
    model = User
    template_name = 'all_users.html'
    context_object_name = 'allusers'

source/accounts/templates/all_users.html
{% extends 'base.html' %}

{% block content %}
    {% for i in allusers %}
        <div class="container card-1 mt-3">
            <p><b>username:</b><a href="{% url 'accounts:detail' i.pk %}">{{ i.username }}</a></p>
            <p><b>first name:</b>{{ i.first_name }}</p>
            <p><b>last name:</b>{{ i.last_name }}</p>
        <p><b>email:</b>{{ i.email }}</p>
        </div>
    {% endfor %}
{% endblock %}

source/accounts/templates/login.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Document</title>
</head>
<body class="login-body">
<h3 class="text-white ml-2"><a href="{% url 'webapp:main_url' %}" class=" text-reset">&lsaquo; Back to main</a></h3>

<div class="card-2 text-center" style="width: 500px; margin-top: 10%; margin-left: 55%">
    <h1 class="text-center mt-5 text-white font-weight-bold">Вход</h1>
    <form action="{% url 'accounts:login' %}" method="post" class="text-center">
        {% csrf_token %}
        {% if has_error %}
            <p class="form-error" style="color: red; background-color: rgba(255,255,255,0.5); border:1px solid red; border-radius: 2px;">Неверное имя пользователя или пароль.</p>
        {% endif %}
        <p><label for="username" class="form-label text-white font-weight-bold">Имя пользователя:</label></p>
        <p><input type="text" name="username" id="username" autofocus style="width: 300px"></p>
        <p><label for="password" class="form-label text-white font-weight-bold">Пароль:</label></p>
        <p><input type="password" name="password" id="password" style="width: 300px"></p>
        <button type="submit" class="login-button">Войти</button>
        <a href="{% url 'accounts:register' %}" class="ml-4 text-white font-weight-bold">Регистрация</a>
    </form>
</div>

</body>
</html>

source/accounts/templates/register.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Roboto:100&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <title>Document</title>
</head>
<body class="login-body">
<h3 class="text-white ml-2"><a href="{% url 'webapp:main_url' %}" class=" text-reset">&lsaquo; Back to main</a></h3>
<h1 style="color: white" class="text-center">Sign Up</h1>
<div style="height: 40vw; width:50%;overflow-y: scroll; color: white; font-weight: bold" class="container card-2">
    <form method="post" action="{% url 'accounts:register' %}" class="text-center">
        {% include 'partial/form.html' with button_text='Register' %}
    </form>
</div>
</body>
</html>

source/accounts/templates/user_change_password.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li class="nav-item active"><a href="{% url 'accounts:detail' user_obj.pk %}" class="nav-link">View</a></li>
        <li class="nav-item active"><a href="{% url 'accounts:user_update' user_obj.pk %}" class="nav-link">Edit Profile</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container card-1 mt-2">
        <h1>Change Password: {{ user_obj.username }}</h1>
        <form action="{% url 'accounts:user_change_password' user_obj.pk %}" method="post">
            {% include 'partial/form.html' with button_text="Save" %}
        </form>
    </div>
{% endblock %}

source/accounts/templates/user_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li class="nav-item active"><a href="{% url "accounts:user_update" user_obj.pk %}" class="nav-link">Edit
            Profile</a></li>
        <li class="nav-item active"><a href="{% url 'accounts:user_change_password' user_obj.pk %}" class="nav-link">Change
            Password</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container card-1 mt-2">

        <h1>Личный кабинет</h1>
        <div class="row">
            <div class="col-sm-4">
                {% if user_obj.profile.avatar %}

                    <img class="avatar" src="{{ user_obj.profile.avatar.url }}" width="250" height="250"
                         alt="user picture">
                {% else %}
                     <img class="avatar" src="{% static 'image/blank.jpg' %}" width="250" height="250"
                         alt="user picture">
                {% endif %}
            </div>
            <div class="col-sm-8">
                <p>Имя пользователя: {{ user_obj.username }}</p>

                <p>Имя: {{ user_obj.first_name }}</p>

                <p>Фамилия: {{ user_obj.last_name }}</p>

                <p>Дата рождения: {{ user_obj.profile.birth_date|date:'d.m.Y' }}</p>

                <p>Почта: {{ user_obj.email }}</p>

                <p>О себе: {{ user_obj.profile.about|default:'(Пусто)' }}</p>

                <p>Github: {{ user_obj.profile.git_hub|default:'(Пусто)' }}</p>
            </div>
        </div>
    </div>
{% endblock %}

source/accounts/templates/user_update.html
{% extends 'base.html' %}
{% block title %}{{ user_obj.username }}{% endblock %}
{% block menu %}
    {% if user_obj == request.user %}
        <li class="nav-item active"><a href="{% url 'accounts:detail' user_obj.pk %}" class="nav-link">View</a></li>
        <li class="nav-item active"><a href="{% url 'accounts:user_change_password' user_obj.pk %}" class="nav-link">Change Password</a></li>
    {% endif %}
{% endblock %}
{% block content %}
    <div class="container card-1 mt-2">
    <h1>Edit Profile: {{ user_obj.username }}</h1>
    <form action="{% url 'accounts:user_update' user_obj.pk %}" method="post" enctype="multipart/form-data">
        {% include 'partial/form.html' with button_text="Update" %}
    </form>
    </div>
{% endblock %}