source/main/urls.py
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include
from django.conf import settings

urlpatterns = [

                  path('admin/', admin.site.urls),

                  path('accounts/', include('accounts.urls')),

                  path('', include('webapp.urls')),

                  path('api/v2/', include('api_v2.urls'))

              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

source/webapp/urls.py
from django.contrib import admin
from django.urls import path
from webapp.views import *

app_name = 'webapp'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', MainPage.as_view(), name='main_url'),
    path('task/<int:pk>/', TaskDetails.as_view(), name='task_details_url'),
    path('task/create/', TaskCreate.as_view(), name='task_create_url'),
    path('task/edit/<int:pk>/', TaskEdit.as_view(), name='task_edit_url'),
    path('task/delete/<int:pk>/', TaskDelete.as_view(), name='task_delete_url'),
    path('status/', StatusView.as_view(), name='status_url'),
    path('type/', TypeView.as_view(), name='type_url'),
    path('type/create/', TypeCreate.as_view(), name='type_create_url'),
    path('status/create/', StatusCreate.as_view(), name='status_create_url'),
    path('status/edit/<int:pk>/', StatusEdit.as_view(), name='status_edit_url'),
    path('status/delete/<int:pk>/', StatusDelete.as_view(), name='status_delete_url'),
    path('type/edit/<int:pk>', TypeEdit.as_view(), name='type_edit_url'),
    path('type/delete/<int:pk>/', TypeDelete.as_view(), name='type_delete_url'),
    path('project/', ProjectView.as_view(), name='project_url'),
    path('project/<int:pk>/', ProjectDetails.as_view(), name='project_details_url'),
    path('project/edit/<int:pk>/', ProjectEdit.as_view(), name='project_edit_url'),
    path('project/delete/<int:pk>/', ProjectDelete.as_view(), name='project_delete_url'),
    path('project/create/', ProjectCreate.as_view(), name='project_create_url'),
    path('project/user/delete/<str:user_1>/<int:id>/', TeamUserDel.as_view(), name='team_user_del_url')
]

source/webapp/models.py
from django.db import models
from django.contrib.auth.models import User

STATUS_CHOICES = (('active', 'Активный'), ('inactive', 'Закрытый'))


class TaskStatus(models.Model):
    status = models.CharField(max_length=100, verbose_name='Статус')

    def __str__(self):
        return self.status


class TaskType(models.Model):
    type = models.CharField(max_length=100, verbose_name='Тип')

    def __str__(self):
        return self.type


class Task(models.Model):
    summary = models.CharField(max_length=100, verbose_name='Краткое описание')
    description = models.TextField(max_length=2000, blank=True, null=True, verbose_name='Полное описание')
    task_status = models.ForeignKey(TaskStatus, on_delete=models.PROTECT, verbose_name='Статус')
    task_type = models.ForeignKey(TaskType, on_delete=models.PROTECT, verbose_name='Тип')
    date_create = models.DateTimeField(auto_now_add=True)
    project = models.ForeignKey('webapp.Project', verbose_name='Проект', related_name='projects', blank=False,
                                null=True, on_delete=models.PROTECT)

    def __str__(self):
        return self.summary[:20]


class Project(models.Model):
    summary = models.CharField(max_length=100, verbose_name='Название проекта')
    description = models.TextField(max_length=2000, blank=True, null=True, verbose_name='Описание')
    date_create = models.DateTimeField(auto_now_add=True)
    date_update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default=STATUS_CHOICES[0][0])

    def delete(self):
        self.status = STATUS_CHOICES[1][0]
        self.save()

    def __str__(self):
        return self.summary[:15]


class Team(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.PROTECT, verbose_name='Пользователь', related_name='team_user')
    project_id = models.ForeignKey(Project, on_delete=models.PROTECT, verbose_name='Проект',
                                   related_name='team_project')
    date_start = models.DateTimeField()
    date_end = models.DateTimeField(null=True, blank=True)

    class Meta:
        permissions = (
            ('can_change_team', 'Can Change Team'),
        )

source/webapp/forms.py
from django import forms
from .models import Task, TaskType, TaskStatus, Project


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ['summary', 'description', 'task_status', 'task_type', 'project']


class StatusForm(forms.ModelForm):
    class Meta:
        model = TaskStatus
        fields = ['status']


class TypeForm(forms.ModelForm):
    class Meta:
        model = TaskType
        fields = ['type']


class ProjectForm(forms.ModelForm):
    class Meta:
        model = Project
        fields = ['summary', 'description']


class SimpleSearchForm(forms.Form):
    search = forms.CharField(max_length=100, required=False, label='Найти')

source/webapp/views/forms.py
from django import forms
from django.contrib.auth.models import User

from webapp.models import Project

source/webapp/views/project.py
from urllib.parse import urlencode

from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render, redirect
from django.utils.timezone import now
from django.views import View
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView

from webapp.forms import SimpleSearchForm, ProjectForm
from webapp.models import Project, Task, STATUS_CHOICES, Team
from django.urls import reverse_lazy


class ProjectView(ListView):
    model = Project
    template_name = 'project/index.html'
    ordering = ['-date_create']

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(
                Q(summary__icontains=self.search_value)
            )
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_search_form(self):
        return SimpleSearchForm(data=self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None


class ProjectDetails(LoginRequiredMixin, DetailView):
    model = Project
    template_name = 'project/details.html'

    def get_context_data(self, **kwargs):
        project = kwargs.get('object')
        tasks = Task.objects.filter(project=project).order_by('date_create')
        context = super().get_context_data(**kwargs)
        paginator = Paginator(tasks, 3, 0)
        page_number = self.request.GET.get('page', 1)
        page = paginator.get_page(page_number)
        slaves = Team.objects.filter(project_id=project).filter(date_end=None).order_by('-date_start')
        seen = []
        keep = []
        for o in slaves:
            if seen.count(o.user_id) == 0:
                keep.append(o)
                seen.append(o.user_id)
        context['slaves'] = keep

        context['paginator'] = paginator
        context['page_obj'] = page
        context['is_paginated'] = page.has_other_pages()
        context['tasks'] = page.object_list
        return context


class ProjectEdit(LoginRequiredMixin, UpdateView):
    model = Project
    template_name = 'project/edit.html'
    fields = ['summary', 'description']
    success_url = reverse_lazy('webapp:project_url')

    def get_context_data(self, **kwargs):
        if self.request.user.has_perm('webapp.change_project') or self.request.user.has_perm('webapp.can_change_team'):
            context = super().get_context_data(**kwargs)
            context['form'] = ProjectForm(instance=self.object)
            users = User.objects.all()
            slaves = Team.objects.filter(project_id=self.object).filter(date_end=None).order_by('-date_start')
            seen = []
            keep = []
            for o in slaves:
                if seen.count(o.user_id) == 0:
                    keep.append(o)
                    seen.append(o.user_id)
            list_users = []
            for i in users:
                list_users.append(i.username)
            print(list_users)
            for i in keep:
                if str(i.user_id) in list_users:
                    list_users.remove(str(i.user_id))
            context['active_users'] = keep
            context['list_users'] = list_users
            return context
        else:
            raise PermissionDenied()

    def form_valid(self, form, *args, **kwargs):
        a = super().form_valid(form)
        users = self.request.POST.getlist('user_list')
        del_users = self.request.POST.getlist('active_users')
        for i in del_users:
            obj = Team.objects.get(pk=i)
            obj.date_end = now()
            obj.save()
        for i in users:
            Team(project_id=self.object, user_id=User.objects.get(username=i), date_start=now()).save()
        return a


class ProjectDelete(LoginRequiredMixin, DeleteView):
    model = Project
    template_name = 'project/delete.html'
    success_url = reverse_lazy('webapp:project_url')
    permission_required = 'webapp.delete_project'


class ProjectCreate(LoginRequiredMixin, CreateView):
    model = Project
    template_name = 'project/create.html'
    fields = ['summary', 'description']
    permission_required = 'webapp.add_project'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        users = User.objects.all()
        list_users = []
        cur_user = self.request.user.username
        for i in users:
            list_users.append(i.username)
        list_users.remove(cur_user)
        context['list_users'] = list_users
        return context

    def get_success_url(self):
        team = Team()
        team.project_id = self.object
        team.user_id = self.request.user
        team.date_start = now()
        team.save()
        return reverse_lazy('webapp:project_url')

    def form_valid(self, form, *args, **kwargs):
        a = super().form_valid(form)
        users = self.request.POST.getlist('user_list')
        for i in users:
            Team(project_id=self.object, user_id=User.objects.get(username=i), date_start=now()).save()
        return a


class TeamUserDel(PermissionRequiredMixin, View):
    permission_required = 'webapp.delete_team'
    def get(self, *args, **kwargs):
        pk = kwargs.get('id')
        idd = kwargs.get('user_1')
        print(pk, idd)
        user_team = Team.objects.filter(pk=pk).filter(user_id=User.objects.get(username=idd)).filter(date_end=None).order_by('-date_start').first()
        user_team.date_end = now()
        user_team.save()
        next = user_team.project_id.id
        return redirect('/project/{}/'.format(next))

source/webapp/views/status.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from webapp.models import TaskStatus
from django.urls import reverse_lazy


class StatusView(ListView):
    template_name = 'status/status_index.html'
    model = TaskStatus


class StatusEdit(LoginRequiredMixin, UpdateView):
    model = TaskStatus
    template_name = 'status/status_edit.html'
    fields = ['status']
    success_url = reverse_lazy('webapp:status_url')


class StatusDelete(LoginRequiredMixin, DeleteView):
    template_name = 'status/status_delete.html'
    model = TaskStatus
    success_url = reverse_lazy('webapp:status_url')


class StatusCreate(LoginRequiredMixin, CreateView):
    model = TaskStatus
    fields = ['status']
    template_name = 'status/status_create.html'
    success_url = reverse_lazy('webapp:status_url')

source/webapp/views/task.py
from urllib.parse import urlencode

from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.core.exceptions import PermissionDenied
from django.db.models import Q
from django.http import Http404
from django.shortcuts import get_object_or_404, render
from django.urls import reverse_lazy
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from webapp.forms import SimpleSearchForm
from webapp.models import Task, STATUS_CHOICES, Team, Project
from django.forms.utils import ErrorList
from django.contrib.auth.decorators import login_required


class TaskDetails(DetailView):
    template_name = 'task/details.html'
    model = Task


class TaskCreate(LoginRequiredMixin, CreateView):
    model = Task
    fields = ['summary', 'description', 'task_status', 'task_type', 'project']
    template_name = 'task/task_create.html'
    success_url = reverse_lazy('webapp:main_url')
    permission_required = 'webapp.add_task'

    def form_valid(self, form):
        project = form.cleaned_data['project']
        team = Team.objects.filter(user_id=self.request.user.id, project_id=project.id)

        if project.status == STATUS_CHOICES[0][0]:
            if team:
                return super().form_valid(form)
            else:
                errors = form._errors.setdefault("project", ErrorList())
                errors.append(u"Вы не в команде!!!")
                return render(self.request, 'task/task_create.html', {'form': form})
        else:
            errors = form._errors.setdefault("project", ErrorList())
            errors.append(u"Вы выбрали неактивный проект!!!")
            return render(self.request, 'task/task_create.html', {'form': form})


class TaskEdit(LoginRequiredMixin, UpdateView):
    model = Task
    template_name = 'task/task_edit.html'
    fields = ['summary', 'description', 'task_status', 'task_type', 'project']
    success_url = reverse_lazy('webapp:main_url')
    permission_required = 'webapp.change_task'

    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        task = get_object_or_404(Task, pk=pk)
        team = Team.objects.filter(user_id=self.request.user.id, project_id=task.project.id)
        if task.project.status == STATUS_CHOICES[0][0] and team:
            return super().get(self, request, *args, **kwargs)
        else:
            raise PermissionDenied()


class TaskDelete(LoginRequiredMixin, DeleteView):
    template_name = 'task/task_delete.html'
    success_url = reverse_lazy('webapp:main_url')
    model = Task
    permission_required = 'webapp.delete_task'

    def get(self, request, *args, **kwargs):
        pk = kwargs.get('pk')
        task = get_object_or_404(Task, pk=pk)
        team = Team.objects.filter(user_id=self.request.user.id, project_id=task.project.id)
        if task.project.status == STATUS_CHOICES[0][0] and team:
            return super().get(self, request, *args, **kwargs)
        else:
            raise PermissionDenied()


class MainPage(ListView):
    template_name = 'task/index.html'
    model = Task
    paginate_by = 3
    paginate_orphans = 1

    def get(self, request, *args, **kwargs):
        self.form = self.get_search_form()
        self.search_value = self.get_search_value()
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.search_value:
            queryset = queryset.filter(
                Q(summary__icontains=self.search_value) |
                Q(description__icontains=self.search_value)
            )
        return queryset

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(object_list=object_list, **kwargs)
        context['form'] = self.form
        if self.search_value:
            context['query'] = urlencode({'search': self.search_value})
        return context

    def get_search_form(self):
        return SimpleSearchForm(data=self.request.GET)

    def get_search_value(self):
        if self.form.is_valid():
            return self.form.cleaned_data['search']
        return None

source/webapp/views/type.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DeleteView
from webapp.forms import TypeForm
from webapp.models import TaskType
from django.urls import reverse_lazy


class TypeEdit(LoginRequiredMixin, UpdateView):
    template_name = 'type/type_edit.html'
    model = TaskType
    fields = ['type']
    success_url = reverse_lazy('webapp:type_url')


class TypeDelete(LoginRequiredMixin, DeleteView):
    template_name = 'type/type_delete.html'
    model = TaskType
    success_url = reverse_lazy('webapp:type_url')


class TypeView(ListView):
    template_name = 'type/type_index.html'
    model = TaskType


class TypeCreate(LoginRequiredMixin, CreateView):
    model = TaskType
    fields = ['type']
    template_name = 'type/type_create.html'
    success_url = reverse_lazy('webapp:type_url')

source/webapp/templates/project/create.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group container mt-5">
                    {% if field.errors %}
                        <div class="alert alert-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                    {{ field.label }}
                    <br/>
                    {{ field }}
                </div>
            {% endfor %}
            <select name="user_list" multiple class="ml-3">
                {% for i in list_users %}
                    <option value="{{ i }}">{{ i }}</option>
                {% endfor %}
            </select>
            <br>
            <button type="submit" class="btn btn-success ml-3 mt-2">Создать</button>
        </form>
    </div>
{% endblock %}

source/webapp/templates/project/delete.html
{% extends 'base.html' %}

{% block content %}
    <div class="container card card-1 text-center mt-5 py-5">
        <h3>Вы точно хотите удалить проект {{ project.summary }}?</h3>
        <form method="post">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">ДА</button>
            <a href="{% url 'webapp:project_url' %}" class="btn btn-primary">НЕТ</a>
        </form>
    </div>
{% endblock %}

source/webapp/templates/project/details.html
{% extends 'base.html' %}

{% block content %}
    <div class="container mt-5 card card-1">
        <h5>Описание: {{ project.summary }}</h5>
        <p>Детальное описание: {{ project.description }}</p>
        <p>Дата создания: {{ project.date_create }}</p>
        <p>Дата изменения: {{ project.date_update }}</p>
        <div>
            <h3>Пользователи:</h3>
            {% for i in slaves %}
                <p>{{ i.user_id }} <i>{{ i.date_start|date:'d-m-Y H:i:s' }}</i></p><a href="{% url 'webapp:team_user_del_url' i.user_id i.pk %}" class="btn-sm btn-danger">x</a>
            {% endfor %}
        </div>
    </div>
    <div class="container my-3">
        <h3>Задачи:</h3>
        <div class="row">
            {% for i in tasks %}
                <div class="col-sm-4 my-2">
                    <div class="card card-1 ">
                        <div id="question_text_{{ i.pk }}">
                            <div class="card-body">
                                <p class="card-text">{{ i.summary }}</p>
                                <hr>
                                <p class="card-text">{{ i.description }}</p>
                                <hr>
                                <p>{{ i.task_status }}</p>
                                <hr>
                                <p>{{ i.task_type }}</p>
                                <a href="{% url 'webapp:task_details_url' i.pk %}"
                                   class="btn btn-primary">Детали</a>
                                {% if project.status == 'active' %}
                                    <a href="{% url 'webapp:task_edit_url' i.pk %}"
                                       class="btn btn-success">Изменить</a>
                                    <a href="{% url 'webapp:task_delete_url' i.pk %}" class="btn btn-danger">X</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            {% endfor %}
            {% if is_paginated %}
                {% include 'partial/pagination.html' %}
            {% endif %}
        </div>
    </div>
{% endblock %}

source/webapp/templates/project/edit.html
{% extends 'base.html' %}

{% block content %}
    <div class="container">
        <form method="post">
            {% csrf_token %}

            {% for field in form %}
                <div class="form-group container mt-5"
                     {% if perms.webapp.change_project %}{% else %}style="display: none" {% endif %}>
                    {% if field.errors %}
                        <div class="alert alert-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                    {{ field.label }}
                    <br/>
                    {{ field }}
                </div>
            {% endfor %}

            <div class="card-1"><p>Пользователи в команде:(выделите, чтобы удалить)</p>
                <select name="active_users" multiple class="ml-3">
                    {% for i in active_users %}
                        <option value="{{ i.pk }}">{{ i.user_id }}</option>
                    {% endfor %}
                </select></div>

            <div class="card-1">
                <p>Добавить пользователей:</p>
                <select name="user_list" multiple class="ml-3">
                    {% for i in list_users %}
                        <option value="{{ i }}">{{ i }}</option>
                    {% endfor %}
                </select></div>
            <button type="submit" class="btn btn-success ml-3 mt-1">Сохранить</button>

        </form>


    </div>

{% endblock %}

source/webapp/templates/project/index.html
{% extends 'base.html' %}
{% block content %}
    {% include 'partial/simple_search.html' %}
    <div class="container mt-5">
        <div class="card-1">
            <h3>Активные</h3>
            <div class="row">
                {% for i in object_list %}
                    {% if i.status == 'active' %}
                        {% include 'partial/project_list.html' %}
                    {% endif %}
                {% endfor %}
            </div>
        </div>
        <div class="card-1 my-5" style="background-color: lightsalmon">
            <h3>Неактивные</h3>
            <div class="row">
                {% for i in object_list %}
                    {% if i.status != 'active' %}
                        {% include 'partial/project_list.html' %}
                    {% endif %}
                {% endfor %}
                {% if is_paginated %}
                    {% include 'partial/pagination.html' %}
                {% endif %}
            </div>
        </div>
    </div>
    <div class="plus-button">
        <a href="{% url 'webapp:project_create_url' %}" class="text-decoration-none">+</a>
    </div>
{% endblock %}